<%
Class HttpStatus
    Public Const CONTINUE = 100
    Public Const SWITCHING_PROTOCOLS = 101
    Public Const PROCESSING = 102
    Public Const EARLY_HINTS = 103
    Public Const OK = 200
    Public Const CREATED = 201
    Public Const ACCEPTED = 202
    Public Const NON_AUTHORITATIVE_INFORMATION = 203
    Public Const NO_CONTENT = 204
    Public Const RESET_CONTENT = 205
    Public Const PARTIAL_CONTENT = 206
    Public Const MULTI_STATUS = 207
    Public Const ALREADY_REPORTED = 208
    Public Const IM_USED = 226
    Public Const MULTIPLE_CHOICES = 300
    Public Const MOVED_PERMANENTLY = 301
    Public Const FOUND = 302
    Public Const SEE_OTHER = 303
    Public Const NOT_MODIFIED = 304
    Public Const USE_PROXY = 305
    Public Const TEMPORARY_REDIRECT = 307
    Public Const PERMANENT_REDIRECT = 308
    Public Const BAD_REQUEST = 400
    Public Const UNAUTHORIZED = 401
    Public Const PAYMENT_REQUIRED = 402
    Public Const FORBIDDEN = 403
    Public Const NOT_FOUND = 404
    Public Const METHOD_NOT_ALLOWED = 405
    Public Const NOT_ACCEPTABLE = 406
    Public Const PROXY_AUTHENTICATION_REQUIRED = 407
    Public Const REQUEST_TIMEOUT = 408
    Public Const CONFLICT = 409
    Public Const GONE = 410
    Public Const LENGTH_REQUIRED = 411
    Public Const PRECONDITION_FAILED = 412
    Public Const PAYLOAD_TOO_LARGE = 413
    Public Const URI_TOO_LONG = 414
    Public Const UNSUPPORTED_MEDIA_TYPE = 415
    Public Const RANGE_NOT_SATISFIABLE = 416
    Public Const EXPECTATION_FAILED = 417
    Public Const IM_A_TEAPOT = 418
    Public Const MISDIRECTED_REQUEST = 421
    Public Const UNPROCESSABLE_ENTITY = 422
    Public Const LOCKED = 423
    Public Const FAILED_DEPENDENCY = 424
    Public Const TOO_EARLY = 425
    Public Const UPGRADE_REQUIRED = 426
    Public Const PRECONDITION_REQUIRED = 428
    Public Const TOO_MANY_REQUESTS = 429
    Public Const REQUEST_HEADER_FIELDS_TOO_LARGE = 431
    Public Const UNAVAILABLE_FOR_LEGAL_REASONS = 451
    Public Const INTERNAL_SERVER_ERROR = 500
    Public Const NOT_IMPLEMENTED = 501
    Public Const BAD_GATEWAY = 502
    Public Const SERVICE_UNAVAILABLE = 503
    Public Const GATEWAY_TIMEOUT = 504
    Public Const HTTP_VERSION_NOT_SUPPORTED = 505
    Public Const VARIANT_ALSO_NEGOTIATES = 506
    Public Const INSUFFICIENT_STORAGE = 507
    Public Const LOOP_DETECTED = 508
    Public Const NOT_EXTENDED = 510
    Public Const NETWORK_AUTHENTICATION_REQUIRED = 511

    Public Shared Function GetDescription(code)
        Select Case code
            Case 100: GetDescription = "Continue"
            Case 101: GetDescription = "Switching Protocols"
            Case 102: GetDescription = "Processing"
            Case 103: GetDescription = "Early Hints"
            Case 200: GetDescription = "OK"
            Case 201: GetDescription = "Created"
            Case 202: GetDescription = "Accepted"
            Case 203: GetDescription = "Non-Authoritative Information"
            Case 204: GetDescription = "No Content"
            Case 205: GetDescription = "Reset Content"
            Case 206: GetDescription = "Partial Content"
            Case 207: GetDescription = "Multi-Status"
            Case 208: GetDescription = "Already Reported"
            Case 226: GetDescription = "IM Used"
            Case 300: GetDescription = "Multiple Choices"
            Case 301: GetDescription = "Moved Permanently"
            Case 302: GetDescription = "Found"
            Case 303: GetDescription = "See Other"
            Case 304: GetDescription = "Not Modified"
            Case 305: GetDescription = "Use Proxy"
            Case 307: GetDescription = "Temporary Redirect"
            Case 308: GetDescription = "Permanent Redirect"
            Case 400: GetDescription = "Bad Request"
            Case 401: GetDescription = "Unauthorized"
            Case 402: GetDescription = "Payment Required"
            Case 403: GetDescription = "Forbidden"
            Case 404: GetDescription = "Not Found"
            Case 405: GetDescription = "Method Not Allowed"
            Case 406: GetDescription = "Not Acceptable"
            Case 407: GetDescription = "Proxy Authentication Required"
            Case 408: GetDescription = "Request Timeout"
            Case 409: GetDescription = "Conflict"
            Case 410: GetDescription = "Gone"
            Case 411: GetDescription = "Length Required"
            Case 412: GetDescription = "Precondition Failed"
            Case 413: GetDescription = "Payload Too Large"
            Case 414: GetDescription = "URI Too Long"
            Case 415: GetDescription = "Unsupported Media Type"
            Case 416: GetDescription = "Range Not Satisfiable"
            Case 417: GetDescription = "Expectation Failed"
            Case 418: GetDescription = "I'm a teapot"
            Case 421: GetDescription = "Misdirected Request"
            Case 422: GetDescription = "Unprocessable Entity"
            Case 423: GetDescription = "Locked"
            Case 424: GetDescription = "Failed Dependency"
            Case 425: GetDescription = "Too Early"
            Case 426: GetDescription = "Upgrade Required"
            Case 428: GetDescription = "Precondition Required"
            Case 429: GetDescription = "Too Many Requests"
            Case 431: GetDescription = "Request Header Fields Too Large"
            Case 451: GetDescription = "Unavailable For Legal Reasons"
            Case 500: GetDescription = "Internal Server Error"
            Case 501: GetDescription = "Not Implemented"
            Case 502: GetDescription = "Bad Gateway"
            Case 503: GetDescription = "Service Unavailable"
            Case 504: GetDescription = "Gateway Timeout"
            Case 505: GetDescription = "HTTP Version Not Supported"
            Case 506: GetDescription = "Variant Also Negotiates"
            Case 507: GetDescription = "Insufficient Storage"
            Case 508: GetDescription = "Loop Detected"
            Case 510: GetDescription = "Not Extended"
            Case 511: GetDescription = "Network Authentication Required"
            Case Else: GetDescription = "Unknown Status Code"
        End Select
    End Function
End Class
%>
